/**
 * Created by twi18192 on 25/08/15.
 */

var appConstants = {
  FOOTER_TOGGLE: "FOOTER_TOGGLE",
  CONFIG_TOGGLE: "CONFIG_TOGGLE",
  FAV_TOGGLE: "FAV_TOGGLE",
  ADD_TAB: "ADD_TAB",
  REMOVE_TAB: "REMOVE_TAB",
  DROPDOWN_SHOW: "DROPDOWN_SHOW",
  DROPDOWN_HIDE: "DROPDOWN_HIDE",
  DROPDOWN_SELECT: "DROPDOWN_SELECT",
  REACTPANEL_SELECT: "REACTPANEL_SELECT",
  REDBLOCKTAB_OPEN: "REDBLOCKTAB_OPEN",

  //REDBLOCKSTATE_CHANGE: "REDBLOCKSTATE_CHANGE",

  BLUEBLOCKTAB_OPEN: "BLUEBLOCKTAB_OPEN",
  GREENBLOCKTAB_OPEN: "GREENBLOCKTAB_OPEN",
  SWITCHTAB_WHENTABOPENS: "SWITCHTAB_WHENTABOPENS",
  PASSING_SIDEPANE: "PASSING_SIDEPANE"
};

module.exports = appConstants;
